AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Moneybird export for Finvision. Retrieves data from Moneybird, stores
  in S3, and returns csv file.

  '
Globals:
  Function:
    Timeout: 10
Metadata:
  AWS::ServerlessRepo::Application:
    Name: mb-finvision-export
    Description: Export function for finvision
    Author: Wouter
    License: license.txt
    ReadmeUrl: s3://moblybird-store/f5dea7efda9c8e093452a5ea30a6525b
    Labels:
    - Moneybird
    - Moblybird
    - Finvision
    - Mobly
    SemanticVersion: 0.0.1
Resources:
  IncomingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://moblybird-store/5fb8ec37c2cd0af59e44f3f50c7c8870
      Handler: app.handler
      Runtime: nodejs10.x
      Events:
        GetIncoming:
          Type: Api
          Properties:
            Path: /incoming
            Method: get
        PostIncoming:
          Type: Api
          Properties:
            Path: /incoming
            Method: post
Outputs:
  GetIncomingApi:
    Description: API Gateway endpoint URL for Prod stage for Incoming function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/incoming/
  PostIncomingApi:
    Description: API Gateway endpoint URL for Prod stage for Incoming function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/incoming/
  IncomingFunction:
    Description: Incoming Lambda Function ARN
    Value:
      Fn::GetAtt:
      - IncomingFunction
      - Arn
  IncomingFunctionIamRole:
    Description: Implicit IAM Role created for Incoming function
    Value:
      Fn::GetAtt:
      - IncomingFunctionRole
      - Arn
